# Generated by Django 5.1 on 2024-08-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(default='==> not specified <==', max_length=30, verbose_name='Идентификатор рейса')),
                ('place_of_departure', models.CharField(max_length=100, verbose_name='Место отправления')),
                ('airline_name', models.CharField(max_length=100, verbose_name='Название авиакомпании')),
                ('number_of_passengers', models.PositiveIntegerField(verbose_name='Количество пассажиров')),
                ('departure_date', models.DateTimeField(verbose_name='Дата вылета')),
            ],
            options={
                'verbose_name': 'Информация о рейсе',
                'verbose_name_plural': 'Информация о рейсе',
            },
        ),
    ]
