# Generated by Django 5.1 on 2024-08-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinfo',
            name='flight_id',
            field=models.CharField(default='==> not specified <==', max_length=64, verbose_name='Идентификатор рейса'),
        ),
    ]
