# Generated by Django 5.1 on 2024-08-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_flightinfo_flight_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightinfo',
            name='place_of_arrival',
            field=models.CharField(default='', max_length=100, verbose_name='Место прибытия'),
        ),
        migrations.AlterField(
            model_name='flightinfo',
            name='place_of_departure',
            field=models.CharField(default='', max_length=100, verbose_name='Место отправления'),
        ),
    ]
