# Generated by Django 5.1 on 2024-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_flightinfo_place_of_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinfo',
            name='flight_id',
            field=models.CharField(default='==> not specified <==', max_length=64, unique=True, verbose_name='Идентификатор рейса'),
        ),
    ]
