# Generated by Django 5.1 on 2024-08-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticketinfo_flight_alter_ticketinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketinfo',
            name='ticket_id',
            field=models.CharField(default='==> not specified <==', max_length=64, unique=True, verbose_name='Идентификатор билета'),
        ),
    ]
